name: nick anderson
tagline: building systems between systems

contact:
  email: nick@morethq.com
  github: iamnande
  linkedin: iamnande

nav:
  items:
    blog:
      title: blog
      path: '/#coming-soon'
      hidden: true
      comingSoon: true

    colophon:
      title: colophon
      url: 'https://github.com/iamnande/iamnande/discussions/13'
      external: true

    philosophy:
      title: philosophy
      path: '/philosophy'

    projects:
      title: projects
      url: 'https://github.com/iamnande?tab=repositories&type=public'
      external: true

  header:
    - philosophy
    - colophon
    - projects

  footer:
    columns:
      - label: nick anderson
        items:
          - philosophy
          - projects
